### ISSUE TITLE
No doc for khm32 and khmx32

### ISSUE THREAD

**Issue by fanghuaqi** [riscv/riscv-p-spec#1]
Hi all, there are no documentation about this `khm32` and `khmx32` instructions, which are listed in this spec, could you check it?

![图片](https://user-images.githubusercontent.com/1538922/85534926-52b75780-b644-11ea-9ea3-88082829c1a3.png)

Thanks
Huaqi

**Comment by chuanhua** [comment]
There are no instructions defined for khm32 and khmx32. They are in the encoding table by mistake. Are you looking for an instruction definition similar to "smmul"?

**Comment by fanghuaqi** [comment]
Ok, thank you, could you update the spec to remove these issue.

**Comment by chuanhua** [comment]
Thanks. I will fix the spec.

**Comment by chuanhua** [comment]
v0.7 specification fixes this issue.
