### ISSUE TITLE
[riscv-b-spec version is v.1.0.0 now]

### ISSUE THREAD

**Issue by fioraking** [riscv/riscv-p-spec#106]
riscv-b-spec version is v.1.0.0 , but riscv-b-spec version is v0.9.3 in this white paper.

**Comment by marcfedorow** [comment]
Zbpbo includes overlaps with insns not described in bitmanip 1.0.0. (e.g. CMIX and funnel shifts)

**Comment by kindleszzw** [comment]
In riscv-p-spec v0.9.9, these pkbb16, pktt16, pkbb32, pktt32 instructions are replaced by pack and packu in the b extension. But in riscv-b-ext v1.0.0, there are no pack and packu instructions.

**Comment by kindleszzw** [comment]
Thank you very much for your replying.
But, I am a newer and I can't understand. I will read this repeatedly to understand it.

**Comment by fioraking** [comment]
I dont care this now, so I prepare to close this issue. and I am doing...
