### ISSUE TITLE
Excess Non-SIMD Q15 insns

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#115]
This is a duplicate of #110
I probably disagree about multiply Q15 insns. Still Q15 word adds does not seem to be hot spot insns.
It seems like a gate from word-wide non-SIMD to halfword-wide SIMD calculations so they should not be called too frequently.

Thus `rv32/kaddh r1 r2 r3` could be replaced with `rv32/kaddw r1 r2 r3; rv32/sclip32 r1 r1 15`.
Same for other [u]k(add|sub)h insns. (<=9.9.1. names)

rv64 could probably have [su]clip insns that perform XLEN-wide clipping.
It makes the same sequence possible.

**Comment by fioraking** [comment]
May kaddw saves more electricity than kaddh does on physical machine?
