### ISSUE TITLE
About the input effective bits size of the KADDH?

### ISSUE THREAD

**Issue by fioraking** [riscv/riscv-p-spec#118]
It should be rs1.h[0] and rs2.h[0]. why is rs1.w[0] and rs2.w[0] ? 
It is very important for me.
please help me. Thank you.

**Comment by fioraking** [comment]
I'm BLUE.

**Comment by chuanhua** [comment]
This has been changed in 5a12c90. Now kaddh/ukaddh/ksubh/uksubh all have 16-bit operands.

**Comment by fioraking** [comment]
Ok, thank you very much.
