### ISSUE TITLE
5.186. WEXTI pseudocode typo

### ISSUE THREAD

**Issue by mkostal-codasip** [riscv/riscv-p-spec#15]
`Idx0 = CONCAT(Rs1(4,1),1’b0); Idx1 = CONCAT(Rs2(4,1),1’b1);
src[63:0] = Concat(R[Idx1], R[Idx0]);
Rd = src[31+LSBloc:LSBloc];`
uses `Rs2` which is not defined for this instruction
change to
`Idx0 = CONCAT(Rs1(4,1),1’b0); Idx1 = CONCAT(Rs1(4,1),1’b1);
src[63:0] = Concat(R[Idx1], R[Idx0]);
Rd = src[31+LSBloc:LSBloc];`

Also suggest to change the syntax
from `WEXTI Rd, Rs1, #LSBloc` to `WEXTI Rd, Rs1, Imm5u` to comply with table 26. That would need to edit the pseudocode accordingly

**Comment by chuanhua** [comment]
Thanks for finding this typo. I will fix this in the next commit.

**Comment by chuanhua** [comment]
Fixed in the v0.9.1 release. (976dbe7)
