### ISSUE TITLE
Suggestion: Zp64 in instruction describtion

### ISSUE THREAD

**Issue by mkostal-codasip** [riscv/riscv-p-spec#17]
I suggest to include information, that an instruction is a part of Zp64 instruction sub-set is added to the detailed description of such an instruction in chapter 5.

**Comment by chuanhua** [comment]
Thanks for the suggestion. This information will be added in the next release of the specification.

**Comment by chuanhua** [comment]
The latest v0.9.4 release has this. This issue can be closed.
