### ISSUE TITLE
Question: Zp64 inclusion of clrov and rdov

### ISSUE THREAD

**Issue by mkostal-codasip** [riscv/riscv-p-spec#18]
Zp64 subset uses saturation instructions, why are not the **clrov** and **rdov** included to manipulate OV bit?

**Comment by chuanhua** [comment]
The intended P extension combination for RV32 is either "Zp-others" or "Zp-others + Zp64". That is why **clrov** and **rdov** are not included in Zp64.

**Comment by chuanhua** [comment]
@mkostal-codasip Can this issue be closed? Thanks.
