### ISSUE TITLE
5.185 URSUBW description typo

### ISSUE THREAD

**Issue by mkostal-codasip** [riscv/riscv-p-spec#21]
In the description section
_This instruction subtracts the first 32-bit **signed** integer in Rs2 from the first 32-bit **signed** integer in Rs1. The 33-bit result is first right-shifted by 1 bit and then sign-extended and written to Rd_
should be **unsigned** instead

Perhaps I should make pull requests for these typos @chuanhua

**Comment by chuanhua** [comment]
Thanks for finding this typo. I will fix it in the next release.

**Comment by chuanhua** [comment]
Fixed in the v0.9.1 release. (976dbe7)
