### ISSUE TITLE
Possible errors in spec require clarification

### ISSUE THREAD

**Issue by taoj33** [riscv/riscv-p-spec#3]
HI, 

When checking the spec we find following mismatches/typos in the spec which may require clarification or correction.

- Instructions only exist in the detailed description but not the instruction list:
      swap16/8, msubr32
- Instructions only exist in the encoding table：
      s/umul16h, s(u)mulx16h, mltbi, mtlei
- possible typos in the encoding table
     ksllw,kslliw  are listed as ksll,kslli
     kmmwat2, kmmwat2 are listed as kmmwt2, kmmwt2.u
     kdmabb16, kdmbb16，khmbb16, kmmawb2.u func7 mismatch with their detailed descriptions

**Comment by chuanhua** [comment]
Thanks for your feedback. I will check and correct these mismatch/errors.

**Comment by taoj33** [comment]
in addition, clo8/16/32 subf5 also mismatch

**Comment by chuanhua** [comment]
Thanks. I have found the subf5 mismatch issues. They will be fixed in the next release.
