### ISSUE TITLE
5.47.2. KMMAWT2.u , 5.78. PBSADA encoding format typo

### ISSUE THREAD

**Issue by hope51607** [riscv/riscv-p-spec#30]
I think  encoding of
```
KMMAWT2.u
1110111
```
```
PBSADA
1110111
```
should be `1111111`

**Comment by jnk0le** [comment]
According to the encoding tables those are still `1111111` in funct7.
Those are also the only instructions with `1111111` in funct7. Probably someone used find and replace during major OP change in 0.9.2
