### ISSUE TITLE
SWAP16 redundant with PKBT16 ?

### ISSUE THREAD

**Issue by rdolbeau** [riscv/riscv-p-spec#32]
Hello,

Isn't SWAP16 redundant when there is PKBT16 in the extension ? As far as I can tell, "PKBT16 a, b, b" is equivalent to "SWAP16 a,b".

Maybe SWAP16 should be made an assembly alias rather than have its own unary opcode ?

**Comment by chuanhua** [comment]
Yes. SWAP16 is redundant. I will make it an assembly alias to "PKBT16 rd, rs, rs". Thanks!

**Comment by chuanhua** [comment]
This issue has been resolved in the latest v0.9.7 release (0560ad6).
