### ISSUE TITLE
inconsistent reg specifier names

### ISSUE THREAD

**Issue by jnk0le** [riscv/riscv-p-spec#35]
Chapter 2 uses `rt, ra, rb` form, which looks like artifact from other architecture, the extension was ported from.
Chapter 5 suddenly switches to `rd, rs1, rs2` form.

There is still a problem with destructive operand naming. `rd` might not be the most convinient, and the crypto group already "invented" `rt` operand as a destructive one, but their `rt` lies in rs1 (that also conflicts with chapter 2 naming).

**Comment by chuanhua** [comment]
Chapter 2 is instruction summary with small table cells. So I have the operand name shortened for operation description in the constrainted space.
Chapter 5 is detailed instruction description, so I used the conventional form of register names.

**Comment by chuanhua** [comment]
Fixed in 20d76b4.
