### ISSUE TITLE
Typo in shortand definitions

### ISSUE THREAD

**Issue by sermazz** [riscv/riscv-p-spec#4]
I would like to report an error at https://github.com/riscv/riscv-p-spec/blob/master/P-ext-proposal.adoc#shorthand-definitions
In the definition `r.H[x]: r[(x*16+7):(x*16+0)]`, `+7` should be a `+15` instead, otherwise the formula to take 32-bit word halves does not work.

**Comment by chuanhua** [comment]
Thanks for spotting this typo. I will fix it in the next release.

**Comment by chuanhua** [comment]
Commit [0a8596a](https://github.com/riscv/riscv-p-spec/commit/0a8596af080f331a91ef0547fa4e357ac2de247d) has fixed this issue.
