### ISSUE TITLE
section 6.22 PKBB32 formatting issue

### ISSUE THREAD

**Issue by mkostal-codasip** [riscv/riscv-p-spec#47]
When describing behaviour of the isntructions, the index of words is somewhat wrogly formated.
Rs1.W[_*0*_] instead of Rs1.W[0] and so on.

**Comment by chuanhua** [comment]
Thanks for finding this issue. It will be fixed in the next release.

**Comment by chuanhua** [comment]
This issue has been fixed in 377b072.
