### ISSUE TITLE
The difference between p-spec and v-spec

### ISSUE THREAD

**Issue by Arima-Kawori** [riscv/riscv-p-spec#50]
We know that P-ext means "packed SIMD" and V-ext means "vector". I've read the docs of v-spec detailedly, and obviously v-ext also provide useful SIMD operations, and some operations are the same with those provided by P-ext. So I'm so curious why P-ext and V-ext are developing simultanously and what the differences between p and v-ext are.
Thanks for anyone who answers my questions!

**Comment by linsinan1995** [comment]
Instructions from P extension operate on general-purpose registers instead of wider vector registers in V extension. This brings advantages, such as flexibility and power efficiency, and constrained devices can be enabled to process with high performance.

**Comment by Arima-Kawori** [comment]
I get it. Thank you for your answer!
