### ISSUE TITLE
KDMATT, KDMABT, KDMATT using V2HImode in RV64P

### ISSUE THREAD

**Issue by linsinan1995** [riscv/riscv-p-spec#51]
instructions, KDMABB, KDMABT, KDMATT, are only three instructions using V2HImode in RV64P. Perhaps it is a typo?

**Comment by chuanhua** [comment]
RV64P `KDMAxx` instructions only use the first 32-bit part of the 64-bit registers as two 16-bit input operands. So the input operand type of `int16x2_t` in the RV64 vector-style intrinsic function is correct. For RV64 SIMD-type of similiar operations, you should use `KDMAxx16` instructions.

**Comment by linsinan1995** [comment]
Does it seem that `kdmxx` also works in this way, but `kdmxx` are using v4hi for 64bit in vector mode.

**Comment by linsinan1995** [comment]
I close this issue since kdmxx in rv64p are changed to v2hi in the commit 86876e75b8f56d2b26b0f813bde5f6ae07f028a6.
