### ISSUE TITLE
Importance of CLO*?

### ISSUE THREAD

**Issue by aswaterman** [riscv/riscv-p-spec#60]
Are the count-leading-ones operations common enough to justify, given that they're equivalent to NOT followed by CLZ*?

**Comment by jnk0le** [comment]
currently code size group has `c.not` under investigation to be included/excluded

**Comment by chuanhua** [comment]
CLZ* is used more often than CLO* from an optimized DSP library source code. And using NOT followed by CLZ* will not hurt too much for performance. I think it is ok to remove CLO* from the P extension.

**Comment by chuanhua** [comment]
Removed `CLO*` instructions in v0.9.6 release.
