### ISSUE TITLE
bitrevi / srai.u encodings in encoding table

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#63]
Table 36. P Extension Instruction Encoding for funct3[14:12]==0b000.
funct7[6:3] = 1110
funct7[101] = 101
Here should be `bitrevi`.

**Comment by chuanhua** [comment]
Thanks for finding this error. I will fix this in the next release.

**Comment by marcfedorow** [comment]
The same issue:
Table 39. P Extension Instruction Encoding for funct3[14:12]==0b001.
funct3 == 001
funct7[6:3] = 1101
funct7[2:0] = 011
Here should be `srai.u`
