### ISSUE TITLE
srai.u encoding in encoding table

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#66]
#63
Table 39. P Extension Instruction Encoding for funct3[14:12]==0b001.
funct3 == 001
funct7[6:3] = 1101
funct7[2:0] = 011
Here should be srai.u

**Comment by chuanhua** [comment]
Thanks. This will be fixed in the next release.

**Comment by chuanhua** [comment]
Fixed in 7ca35508bf5.
