### ISSUE TITLE
KMMAWT2[.u] similar chunks

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#70]
`1110111_00000_00000_001_00000_1110111` can be both `KMMAWT2 x0 x0 x0` and `KMMAWT2.u x0 x0 x0` according to 5.47.
As I may suppose from Table 39 `KMMAWT2.u`'s real encoding is `1111111_...`.

Same for PBSADA

**Comment by jnk0le** [comment]
#30

**Comment by marcfedorow** [comment]
@jnk0le it seems like old issues are not checked.
Anyway thanks for pointing this out

**Comment by topperc** [comment]
I made a pull request here https://github.com/riscv/riscv-p-spec/pull/72.  Should have checked the issues first

**Comment by chuanhua** [comment]
I have merged the pull requests. Thanks.
