### ISSUE TITLE
WoRd

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#75]
`Multiply and Add to 32-bit WoRd`
I believe this is a replace-all issue

**Comment by chuanhua** [comment]
Thanks. I will fix this in the next release.

**Comment by chuanhua** [comment]
Fixed in [7ca35508bf5](https://github.com/riscv/riscv-p-spec/commit/7ca35508bf5a618afd5658269e9918bfcdab705b).
