### ISSUE TITLE
No need in Zprvsfextra subset

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#76]
Look how subsets in k-ext are chosen.
They are divided by logic of its insns, not by xlen.
Without loss of generality, let's take a look at Zknh subset. It includes four `sha256*` insn (both rv32 and rv64), six `sha512*` rv32-only insns and four `sha512*` rv64-only insns.
In this terms there is no need in Zprvsfextra subset. Zprvsfextra subset should be merged with Zpn subset (so Zpn will contain both current-Zpn and current-Zprvsfextra with rv64-only label).
This allows more smooth subset expanding support and it is more consistent with the other extensions.
Check [this](https://github.com/riscv/riscv-gcc/pull/258/files#r686711866) as an illustration.

**Comment by chuanhua** [comment]
This makes sense. I will merge Zprvsfextra into Zpn. Thanks!
