### ISSUE TITLE
Intrinsic naming

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#84]
The use of two underscores in identifiers is reserved
for the compiler's internal use according to the ANSI-C standard.
Intrinsics are indeed "the compiler's internal" stuff.
This means that B-ext and K-ext scheme are most likely improper.
Still two underscores **after** `__rv` seem to be redundant.
`__rv_insn` and `__rv_v_insn` could probably be the best decision.
See also: https://github.com/riscv/riscv-p-spec/issues/44, https://github.com/riscv/riscv-c-api-doc/issues/18

**Comment by chuanhua** [comment]
Changed "`__rv__`" prefix to "`__rv_`" in v0.9.6 release (0eeb572)
