### ISSUE TITLE
Make add64 an alias on rv64

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#87]
`ADD64` should be an alias of `ADD` on rv64 as `KMADA32` is an alias of `KMAR64`
See [this omment](https://github.com/riscv/riscv-p-spec/issues/39#issuecomment-916495963) for more information.

**Comment by jnk0le** [comment]
#39

**Comment by chuanhua** [comment]
Removed RV64 add64 in b2fffab.
