### ISSUE TITLE
No need in RVM overlaps

### ISSUE THREAD

**Issue by marcfedorow** [riscv/riscv-p-spec#95]
P-ext does not require SRL/SRA while it is represented in I extension.
P-ext does not require regular MUL while it is represented in M extension.
There is no logic in requiring some "special" mul while not requiring "regular" ones.
P-ext spec should just say that M extension is mandatory. Requiring some specific mul is redundant.

**Comment by chuanhua** [comment]
Yes. It is a bit redundant. I will fix it. Thanks!

**Comment by chuanhua** [comment]
Removed Zmpmo in b2fffab.
